# Generated by Django 5.0.3 on 2024-03-15 01:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
